apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Tools\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: api1
  name: api1
spec:
  ports:
    - name: "50001"
      port: 50001
      targetPort: 80
    - name: "50002"
      port: 50002
      targetPort: 443
  selector:
    io.kompose.service: api1
status:
  loadBalancer: {}
