version: "3"
services:
  api1:
    build: ./Api1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "50001:80"
      - "50002:443"
  api2:
    build: ./Api2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - WebApiBaseAddress=http://api1
    ports:
      - "50003:80"
      - "50004:443"
